print (",-------------------------------,")
print ("| Y C Y G W R P K H O A B U V H |")
print ("| S C I R F Z B M C P M Y C F P |")
print ("| U A F R X T W L O T A S M X C |")
print ("| E J R A G S A V H G L R X G F |")
print ("| K X Z T A P C V J Q M J Y M G |")
print ("| G C X Q E W S I A L A E O I V |")
print ("| I F Y F X V A L P A L H E T A |")
print ("| L E K O U U T I G U A N C O I |")
print ("| V H I H Z U A I F R D B A L U |")
print ("| A R Z H X C L C O G E E X V R |")
print ("| U N B S T M U S I C A T L A A |")
print ("| W R A U J A B I S S N O R I S |")
print ("| C M P L E N P A L C O A H B E |")
print ("| T M F O T Z M P T R E S J R L |")
print ("| F S I K U F P E Q T A M L O J |")
print ("'-------------------------------'")
palavra = input("")
